project:
  title: "Jakub Štenc"
  output-dir: ./docs/cz

website:
  page-navigation: true
  favicon: "images/pyl.png"
  site-url: "https://jakubstenc.github.io/jakubstenc"
  navbar:
    logo: "images/pyl.png"
    logo-href: index.html
    left:
      - href: index.qmd#aboutme 
        text: O mě
      - href: index.qmd#CVtag
        text: Životopis
      - href: index.qmd#researchtopics
        text: Výzkumná témata
      - href: https://pollination-ecology-group.github.io/Pollination_ecology_group/Pollination_Ecology_Group.html#index
        text: Pollination Ecology Group
      - href: index.qmd#contanctme
        text: Kontaktujte mě  
      - href: news.qmd
        text: Novinky 
    right:
      - icon: github
        href: https://github.com/jakubstenc
      - text: "{{< ai google-scholar size=2x >}}"
        aria-label: Google Scholar
        href: https://scholar.google.com/citations?user=xxxxx=en
      - text: "{{< ai orcid size=2x >}}"
        aria-label: ORCID
        href:  https://orcid.org/0000-0003-0678-8452
      - href: ../
        text: English
  page-footer: 
    left: "Copyright 2024, Jakub Štenc" 

lang: cs
format:
  html:
    theme: sandstone
    toc: true
    smooth-scroll: true
extensions:
  iconify:
    set: "octicon"
    size: "Huge"
    width: "1em"
    height: "1em"
    flip: "horizontal"
    rotate: "90deg"
    inline: true
    mode: "svg"
    style: "color: #b22222;"
