project:
  title: "Jakub Štenc"
  output-dir: ./docs
  render:
    - "*.qmd"
    - "!archive/"
  
website:
  page-navigation: true  
  navbar:
    logo: "images/pyl.png"
    href: about.qmd    
    left:
      - href: about.qmd#about
        text: About me 
      - href: about.qmd#CVen
        text: CV
      - href: about.qmd#research
        text: Research
      - href: https://pollination-ecology-group.github.io/Pollination_ecology_group/Pollination_Ecology_Group.html#about
        text: Pollination Ecology Group
      - href: news.qmd
        text: News
    right:
      - icon: github
        href: https://github.com/jakubstenc
      - text: "{{< ai google-scholar size=2x >}}"
        aria-label: Google Scholar
        href: https://scholar.google.com/citations?user=xxxxx=en
      - text: "{{< ai orcid size=2x >}}"
        aria-label: ORCID
        href:  https://orcid.org/0000-0003-0678-8452
      - href: /cz/about.html
        text: Česky
  page-footer: 
    left: "Copyright 2024, Jakub Štenc" 
lang: en
format:
  html:
    theme: sandstone
    toc: true
    toc-depth: 3
extensions:
  iconify:
    set: "octicon"
    size: "Huge"
    width: "1em"
    height: "1em"
    flip: "horizontal"
    rotate: "90deg"
    inline: true
    mode: "svg"
    style: "color: #b22222;"