project:
  title: "Jakub Štenc"
  output-dir: ./docs/cz

website:
  navbar:
    logo: "images/pyl.png"
    href: about.qmd    
    left:
      - href: about.qmd#ome 
        text: O mě
      - href: about.qmd##CVcze 
        text: Životopis
      - href: research.qmd
        text: Výzkumná témata
      - href: https://pollination-ecology-group.github.io/Pollination_ecology_group/Pollination_Ecology_Group.html#about
        text: Pollination Ecology Group
      - href: news.qmd
        text: Novinky 
    right:
      - icon: github
        href: https://github.com/jakubstenc
      - text: "{{< ai google-scholar size=2x >}}"
        aria-label: Google Scholar
        href: https://scholar.google.com/citations?user=xxxxx=en
      - text: "{{< ai orcid size=2x >}}"
        aria-label: ORCID
        href:  https://orcid.org/0000-0003-0678-8452
      - href: ../
        text: English
  page-footer: 
    left: "Copyright 2024, Jakub Štenc" 

lang: cs
format:
  html:
    theme: sandstone
    toc: true
    toc-depth: 3
