project:
  title: "Jakub Štenc"
  output-dir: ./docs/cz

website:
  navbar:
    logo: "images/pyl.png"
    href: about.qmd    
    left:
      - href: about.qmd#ome 
        text: O mě
      - href: CV.qmd
        text: Životopis
      - href: research.qmd
        text: Výzkumná témata
      - href: PEG.qmd
        text: Pollination Ecology Group
      - href: news.qmd
        text: Novinky 
    right:
      - icon: github
        href: https://github.com/jakubstenc
      - icon: twitter
        href: https://twitter.com/Cotylledon
      - text: "{{< ai google-scholar size=xl >}}"
        href: https://scholar.google.com/citations?user=xxxxx=en
      - icon: orcid 
        text: "{{< ai orcid size=xl >}}"
        href: https://orcid.org/0000-0003-0678-8452
      - href: ../
        text: English
  page-footer: 
    left: "Copyright 2024, Jakub Štenc" 

lang: cs
format:
  html:
    theme: sandstone
    toc: true
    toc-depth: 3
